#
# Copyright 2011-2023 Branimir Karadzic. All rights reserved.
# License: https://github.com/bkaradzic/bgfx/blob/master/LICENSE
#

BGFX_DIR=../../bgfx.cmake
RUNTIME_DIR=../
BUILD_DIR=../../build

include ../../bgfx.cmake/bgfx/scripts/shader.mk
